robot_frame: robot_base_footprint
map_frame: robot_map

planners:
  - name: GlobalPlanner
    type: global_planner/GlobalPlanner

controllers:
  - name: TebLocalPlannerROS
    type: teb_local_planner/TebLocalPlannerROS

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 1.0
planner_patience: 5.0

oscillation_timeout: 10.0
oscillation_distance: 0.2

recovery_behaviors:
  - name: rotate_recovery
    type: rotate_recovery/RotateRecovery
  - name: clear_costmap_recovery
    type: clear_costmap_recovery/ClearCostmapRecovery

recovery_enabled: true
recovery_patience: 15.0