footprint: [[0.65, -0.38], [0.65, 0.38], [-0.60,0.38], [-0.6, -0.38]]

publish_frequency: 1.0

inflation_layer:
  inflation_radius: 0.3

obstacle_laser_layer:
  obstacle_range: 2.5
  raytrace_range: 5.5
  observation_sources: front_laser rear_laser
  front_laser: 
    sensor_frame: robot_front_laser_link
    data_type: LaserScan
    topic: $(arg front_scan_topic)
    marking: true
    clearing: true
  rear_laser: 
    sensor_frame: robot_rear_laser_link
    data_type: LaserScan
    topic: $(arg rear_scan_topic)
    marking: true
    clearing: true


