global_costmap:
  global_frame: robot_map
  robot_base_frame: robot_base_footprint
  update_frequency: 5.0
  rolling_window: false
  width: 100.0 # this are overwritten static_layer receives a map
  height: 100.0 # this are overwritten static_layer receives a map
  resolution: 0.05 # this are overwritten static_layer receives a map
  static_map: true

  plugins:
    - name: static_map
      type: "costmap_2d::StaticLayer"
# obstacle layers could also be included in global costmap
#    - name: obstacle_laser_layer
#      type: "costmap_2d::VoxelLayer"
#    - name: rgbd_obstacle_layer
#      type: "costmap_2d::VoxelLayer"
#    - name: costmap_prohibition_layer
#      type: "costmap_prohibition_layer_namespace::CostmapProhibitionLayer"
    - name: inflation_layer
      type: "costmap_2d::InflationLayer"

  static_map:
    enabled: true
    lethal_cost_threshold: 94
    static_map: true
    map_topic: map
    unknown_cost_value: 1
    trinary_costmap: false
    use_maximum: false
